### ISSUE TITLE
Unable to save a phone number when using UUIDs

### ISSUE THREAD

**Issue by mainangethe** [cerebris/peeps#14]
I tried recreating Peeps as the tutorial suggests in README.md with only one (1) difference: using UUIDs instead of Int Primary keys.

I was able to go to the point of creating items while testing the APIs. 
This is where I am currently stuck; I am unable to create a phone number. 

It keeps giving a response that the field value is invalid.
Code: 103
Status: 400"
Detail: "bc846a91-e442-4a12-aa4a-7f218e85e1f4 is not a valid value for id."

SIDE NOTE:
I even created a second contact and tried using his UUID instead but to no avail.

SCREENSHOT
![tiny-peeps-error-b](https://user-images.githubusercontent.com/41260290/57839023-8895d580-77ce-11e9-980c-1b2df5053964.jpg)

**Comment by mainangethe** [comment]
Found the solution after reading the documentation.
http://jsonapi-resources.com/v0.10/guide/resources.html#Override-key-type-on-a-resource

```ruby
key_type :uuid
```
Solves the issue

**Comment by lgebhardt** [comment]
Glad you found it. We also have the https://github.com/cerebris/peeps-uuids project to look at. It needs an update, but everything should work. Looks like I should add a link in the JR docs to that as well.
