### ISSUE TITLE
linkage broken?

### ISSUE THREAD

**Issue by with-heart** [cerebris/peeps#2]
Hello!

I followed along with the tutorial and believe I have run into an issue. 

The third to last step lists the curl command as follows: `curl -i -H "Accept: application/vnd.api+json" "http://localhost:3000/contacts?include=phone-numbers"` This is supposed to result in a json reply that contains direct phone number information. However, running that code results in a linkage of "[]": 

`{"data":[{"id":"1","name-first":"John","name-last":"Doe","email":"john.doe@boring.test","twitter":null,"type":"contacts","links":{"self":"http://localhost:3000/contacts/1","phone-numbers":{"self":"http://localhost:3000/contacts/1/links/phone-numbers","related":"http://localhost:3000/contacts/1/phone-numbers","linkage":[]}}}]}`

The second to last step lists the following curl command: `curl -i -H "Accept: application/vnd.api+json" "http://localhost:3000/contacts?include=phone-numbers&fields%5Bcontacts%5D=name-first,name-last&fields%5Bphone-numbers%5D=name"` This correctly displays the fields, but the phone number is nowhere to be found:

`{"data":[{"name-first":"John","name-last":"Doe","type":"contacts","id":"1","links":{"self":"http://localhost:3000/contacts/1"}}]}`

Retrieving the full list of phone numbers results in the following:
`{"data":[{"id":"1","name":"home","phone-number":"(513)377-7911","type":"phone_numbers","links":{"self":"http://localhost:3000/phone-numbers/1","contact":{"self":"http://localhost:3000/phone-numbers/1/links/contact","related":"http://localhost:3000/phone-numbers/1/contact","linkage":null}}}]}`

In all cases, linkage and directly embedding link information appears to be broken. Have I done something wrong?

**Comment by amikula** [comment]
I ran into exactly the same problem! It works if you use 0.3.0.pre1 in your Gemfile. Seems like a bug in 0.3.1 to me.

**Comment by lgebhardt** [comment]
In JR release 0.3.1 the format for linkage format changed. I've updated the Peeps app, along with the readme. The problem is the phone number was not being associated with the contact when it was being created. The updated code to create the phone number is:

```bash
curl -i -H "Accept: application/vnd.api+json" -H 'Content-Type:application/vnd.api+json' -X POST -d '{"data": {"type":"phone-numbers", "links": {"contact": {"linkage": {"type": "contacts", "id":"1"}}}, "name":"home", "phone-number":"(603) 555-1212"}}' "http://localhost:3000/phone-numbers"
```

Note the `linkage` hash key.

I've added issue #170 to address the fact that no error is being raised.

**Comment by growlove** [comment]
Thanks a lot @lgebhardt.

**Comment by amikula** [comment]
Yeah thanks!

**Comment by lolmaus** [comment]
Both the readme and migrations are missing a foreign key. Adding a related record results in a internal server error.
